[project]
name = "time-series-analysis-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "prophet>=1.1.7",
    "scikit-learn>=1.7.2",
]
